# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: svix
before:
  hooks:
    - go mod tidy
builds:
  - id: svix
    ldflags:
      - -s -w -X github.com/svix/svix-cli/version.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
nfpms:
  - builds:
      - svix
    vendor: Svix
    homepage: https://www.svix.com
    maintainer: Svix <support@svix.com>
    description: Svix CLI utility
    formats:
      - deb
      - rpm
      - apk
brews:
  - repository:
      owner: svix
      name: homebrew-svix
    commit_author:
      name: svix-ci
      email: support@svix.com
    homepage: https://www.svix.com
    description: Svix CLI utility
    install: |
      bin.install "svix"
    caveats: "Thanks for installing the Svix CLI! If this is your first time using the CLI, checkout our docs at https://docs.svix.com."
scoops:
  -
    repository:
      owner: svix
      name: scoop-svix
    commit_author:
      name: svix-ci
      email: support@svix.com
    homepage: https://www.svix.com
    description: Svix CLI utility
snapcrafts:
  -
    name: svix
    publish: true
    summary: Svix CLI utility
    description: |
      Svix makes it easy to send webhook from your service while ensuring robust deliverability and a great developer experience for your users.
      You can think of it as webhooks as a service. https://docs.svix.com/
    grade: stable
    confinement: strict
    license: GPL-3.0
    base: core20

    apps:
      svix:
        plugs: ["network"]
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
